[package]
name = "weather-station"
version = "0.1.0"
authors = ["EricKulchycki <erickulchycki@gmail.com>"]
edition = "2018"

[dependencies]
bme280 = "0.2.1"
linux-embedded-hal = "0.3.0"
nb = "1"
libsqlite3-sys = "0.20.1"

[dependencies.rusqlite]
version = "0.24.2"
features = ["bundled"]